---
name: "pre-release"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        
      - name: Build with Maven
        run: |
            mvn clean verify assembly:single
            echo 'Development Build successfully created.'

      - uses: "marvinpinto/action-automatic-releases@latest"
        id: releaser
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "dev-snapshot-${{ steps.vars.outputs.sha_short }}"
          prerelease: true
          title: "RoseDB - Development Build ${{ steps.vars.outputs.sha_short }}"
          files: |
            target/*.jar
