---
name: "pre-release"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
        
      - name: Build with Maven
        run: |
            mvn clean verify assembly:single
            echo 'Development Build successfully created.'

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "dev-snapshot-${GITHUB_SHA::6}"
          prerelease: true
          title: "RoseDB - Development Build ${{ github.event.release.tag_name }} | ${GITHUB_SHA::6}"
          files: |
            /target/*.jar
